spring:
  application:
    name: Community Issue Portal

  datasource:
    url: jdbc:mysql://localhost:3306/ipapp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${mysql_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # options: none, update, create, create-drop, validate
      show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwtSecret: "LongestStringIEverCreatedInMyEntireCareerSoFarOnFifthJanuary2026"
  jwtExpirationInMs: 36000000